#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/ecommerce_app?useSSL=false&serverTimezone=UTC
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver

    spring:
      application:
        name: ecommerce-app
      datasource:
        url: jdbc:mysql://localhost:3306/ecommerce_app?useSSL=false&serverTimezone=UTC
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver